INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('1', '2', '6', '1', 'TUNER');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('2', '7', '7', '1', 'BLISTER PACKING OR VINLY PACKING');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('3', '8', '18', '1', 'ACCESSORIES');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('4', '19', '37', '1', 'STRING');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('5', '38', '53', '1', 'MACHINE HEAD OR TUNING KEY');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('6', '54', '59', '1', 'WILKINSON MACHINE HEAD');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('7', '60', '60', '1', 'FRET WIRE OR ABS BINDING');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('8', '61', '63', '1', 'TRUSS ROD');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('9', '64', '125', '1', 'HARDWARE');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('10', '126', '130', '1', 'WILKINSON HARDWARE');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('11', '131', '134', '1', 'ELECTRONIC');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('12', '135', '135', '1', 'SWITCH');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('13', '136', '136', '1', 'JACK');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('14', '137', '141', '1', 'KNOB');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('15', '142', '146', '1', 'NUT');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('16', '147', '148', '1', 'SADDLE');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('17', '149', '150', '1', 'BACK COVER');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('18', '151', '151', '1', 'BRIDGE PIN OR END PIN');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('19', '152', '231', '1', 'PICKUP PART');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('20', '232', '232', '1', 'VIOLIN OR CELLO');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('21', '233', '241', '1', 'WILKINSON PICKUP');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('22', '242', '280', '1', 'PICKUP');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('23', '281', '306', '1', 'EQUALIZER');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('24', '307', '307', '1', 'PICKGUARD');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('25', '308', '308', '1', 'ASSEMBLIES');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('26', '309', '312', '1', 'POSITION MARK');
INSERT INTO `swmusic`.`Content` (`id`, `startPage`, `endPage`, `catalogId`, `name`) VALUES ('27', '313', '313', '1', 'WOOD BRIDGE');
