import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { TransformWrapper, TransformComponent } from "react-zoom-pan-pinch";
import Slider, { Settings } from "react-slick";

const index: NextPage = () => {
  const settings: Settings = {
    dots: false,
    arrows: true,
    infinite: false,
    speed: 500,
    slidesToShow: 1,
    swipe: false,
  };

  return (
    <div className="">
      <Head>
        <title>SAMWOO MANUFACTURING CO., LTD.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-slate-400 relative">
        <div style={{ width: "50rem", height: "50rem" }} className="relative">
          <div className="flex w-full h-full relative">
            <Image
              src={"http://146.56.147.155/images/1.JPG"}
              alt="신발"
              layout="fill"
            ></Image>
          </div>
          <div className="flex w-full h-full relative">
            <Image
              src={"http://146.56.147.155/images/2.JPG"}
              alt="신발"
              layout="fill"
            ></Image>
          </div>
          <div className="flex w-full h-full relative">
            <Image
              src={"http://146.56.147.155/images/3.JPG"}
              alt="신발"
              layout="fill"
            ></Image>
          </div>
        </div>
      </div>
    </div>
  );
};

export default index;
