import Head from "next/head";
import { RecoilRoot } from "recoil";
import Header from "./Header";

const Layout = (props: any) => {
  return (
    <>
      <Head>
        <title>SAMWOO MANUFACTURING CO., LTD.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="initial-scale=1.0, width=device-width, user-scalable=no,maximum-scale=1.0,minimum-scale=1.0"
        />
      </Head>
      <div className="">
        <div className="bg-slate-100 h-screen flex justify-center items-center">
          <Header></Header>
          {props.children}
        </div>

        <div className="">Footer</div>
      </div>
    </>
  );
};

export default Layout;
