import Head from "next/head";
import { useEffect, useState } from "react";
import Footer from "./Footer";
import Header from "./Header";

const Layout = (props: any) => {
  const [isIE, setIsIE] = useState(false);

  useEffect(() => {
    setIsIE(/MSIE|Trident/.test(window.navigator.userAgent));
    return () => {};
  }, []);

  return (
    <>
      <Head>
        <title>SAMWOO MANUFACTURING CO., LTD.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="initial-scale=1.0, width=device-width, user-scalable=no,maximum-scale=1.0,minimum-scale=1.0"
        />
      </Head>
      <div className="">
        {isIE && (
          <div className="z-50">
            This site does not support IE11. Please use a modern browser such as
            Edge or Chrome.
          </div>
        )}
        <div className="bg-slate-100 flex justify-center items-center">
          <Header></Header>
          {props.children}
        </div>
        <Footer></Footer>
      </div>
    </>
  );
};

export default Layout;
