import type { NextPage } from "next";
import Head from "next/head";

import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { getPlaiceholder } from "plaiceholder";
import Link from "next/link";
import { atom, useRecoilState, useRecoilValue } from "recoil";
import { categoryNaviState, countState } from "../components/state/atomState";
import { animated, useSpring } from "react-spring";
import MainPage from "../components/MainPage";

export const getStaticProps = async () => {
  const { base64, img } = await getPlaiceholder(
    "http://146.56.147.155/images/2.JPG"
  );

  return {
    props: {
      imageProps: {
        ...img,
        blurDataURL: base64,
      },
    },
  };
};

const Home: NextPage = ({ imageProps }: any) => {
  const [show, setShow] = useRecoilState(categoryNaviState);

  const [countnumber, api] = useSpring(() => ({
    number: 0,
    config: { mass: 5, tension: 350, friction: 40 },
  }));
  const count = useRecoilValue(countState);
  setShow(false);
  return (
    <div className="">
      <Head>
        <title>SAMWOO MANUFACTURING CO., LTD.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center">
        <MainPage></MainPage>
        {/* <Link href="/catalog/3">Catalog 1</Link>
        <Link href="/catalog/1">Catalog 2</Link>
        <h1>
          <h1>{`show=${show} / count=${count}`}</h1>
        </h1>

        <h6>testsetsetstsetsetsetsetsetsetsetsetsetset</h6>
        <animated.div>{countnumber.number}</animated.div>

        <div
          onMouseEnter={() => api.start({ number: 1000 })}
          onMouseOut={() => api.stop()}
          className="rounded p-3 bg-red-200 cursor-pointer hover:bg-red-300"
        >
          Hover me
        </div> */}
      </div>
    </div>
  );
};

export default Home;
