import type { NextPage } from "next";
import Head from "next/head";

import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { getPlaiceholder } from "plaiceholder";
import Link from "next/link";
import { atom, useRecoilValue } from "recoil";
import { categoryNaviState } from "../components/state/atomState";

export const getStaticProps = async () => {
  const { base64, img } = await getPlaiceholder(
    "http://146.56.147.155/images/2.JPG"
  );

  return {
    props: {
      imageProps: {
        ...img,
        blurDataURL: base64,
      },
    },
  };
};

const Home: NextPage = ({ imageProps }: any) => {
  const state = useRecoilValue(categoryNaviState);

  console.log(state);
  return (
    <div className="">
      <Head>
        <title>SAMWOO MANUFACTURING CO., LTD.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center py-16 h-screen">
        <Link href="/catalog/3">Catalog 1</Link>
        <Link href="/catalog/1">Catalog 2</Link>
      </div>
    </div>
  );
};

export default Home;
