import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { TransformWrapper, TransformComponent } from "react-zoom-pan-pinch";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const Home: NextPage = () => {
  const settings = {
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1,
  };

  return (
    <div>
      <Head>
        <title>SAMWOO MANUFACTURING CO., LTD.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-96  h-96 relative">
        <Slider {...settings}>
          <TransformWrapper>
            <TransformComponent>
              <div className="w-96  h-96 flex relative">
                <Image
                  src={"http://146.56.147.155/images/1.JPG"}
                  alt="신발"
                  layout="fill"
                ></Image>
              </div>
            </TransformComponent>
          </TransformWrapper>
          <div className="w-96 h-96 flex relative">
            <Image
              src={"http://146.56.147.155/images/2.JPG"}
              alt="신발"
              layout="fill"
            ></Image>
          </div>
          <div className="w-96 h-96 flex relative">
            <Image
              src={"http://146.56.147.155/images/3.JPG"}
              alt="신발"
              layout="fill"
            ></Image>
          </div>
        </Slider>
      </div>
    </div>
  );
};

export default Home;
